{{- include "demo-linkops.template" (dict "name" "frontend" "port" .Values.frontend.port "image" .Values.frontend.image "ctx" .) }}
---
{{- include "demo-linkops.template" (dict "name" "api" "port" .Values.api.port "image" .Values.api.image "ctx" .) }}
---
{{- include "demo-linkops.template" (dict "name" "rag" "port" .Values.rag.port "image" .Values.rag.image "ctx" .) }}
---
{{- include "demo-linkops.template" (dict "name" "sync" "port" .Values.sync.port "image" .Values.sync.image "ctx" .) }}
---
{{- include "demo-linkops.template" (dict "name" "models" "port" .Values.models.port "image" .Values.models.image "ctx" .) }}
---
{{- include "demo-linkops.template" (dict "name" "pipeline" "port" .Values.pipeline.port "image" .Values.pipeline.image "ctx" .) }}