apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo-linkops-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - host: demo.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: frontend
                port:
                  number: {{ .Values.frontend.port }}
          - path: /api
            pathType: Prefix
            backend:
              service:
                name: api
                port:
                  number: {{ .Values.api.port }}
          - path: /rag
            pathType: Prefix
            backend:
              service:
                name: rag
                port:
                  number: {{ .Values.rag.port }}
          - path: /sync
            pathType: Prefix
            backend:
              service:
                name: sync
                port:
                  number: {{ .Values.sync.port }}
          - path: /models
            pathType: Prefix
            backend:
              service:
                name: models
                port:
                  number: {{ .Values.models.port }}
          - path: /pipeline
            pathType: Prefix
            backend:
              service:
                name: pipeline
                port:
                  number: {{ .Values.pipeline.port }}