{{- range $name, $svc := dict "frontend" .Values.frontend "api" .Values.api "rag" .Values.rag "sync" .Values.sync "models" .Values.models "pipeline" .Values.pipeline }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.global.namespace }}
spec:
  selector:
    app: {{ $name }}
  ports:
    - protocol: TCP
      port: {{ $svc.port }}
      targetPort: {{ $svc.port }}
---
{{- end }}